// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVVdFQfadKQwbGfuvHdlF_SnYuEBLJLo',
    appId: '1:292260440690:android:8255496b5ec64e0632f0eb',
    messagingSenderId: '292260440690',
    projectId: 'ecommerceapp-ea54f',
    storageBucket: 'ecommerceapp-ea54f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-qrPL36ZRwEY8PQe-ZnEHZeekRQt-F2Y',
    appId: '1:292260440690:ios:3cdb81a4ffbbc4f032f0eb',
    messagingSenderId: '292260440690',
    projectId: 'ecommerceapp-ea54f',
    storageBucket: 'ecommerceapp-ea54f.firebasestorage.app',
    iosClientId: '292260440690-6r6bdd8r6ouv9gfs0v69e8ujb618m6lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

}